# 루트 쿼리
type Query {
    """
    모든 통화의 환율 정보를 조회합니다.
    """
    ExchangeRateResponseDTO: ExchangeRateResponseDTO

    """
    특정 통화 코드 리스트를 받아 해당 환율 정보만 조회합니다.
    """
    specificExchangeRates(currencyCodes: [String!]!): ExchangeRateResponseDTO

    """
    모든 할 일 목록을 조회합니다.
    """
    todos: [Todo]
}

# 환율(Exchange Rate) 관련 타입
"""
환율 API의 전체 응답
"""
type ExchangeRateResponseDTO {
    rates: [ExchangeRate]
    executionTimeMs: Int
}

"""
개별 통화와 환율 정보
"""
type ExchangeRate {
    currency: String!
    rate: String!
}



# 할 일 목록
"""
개별 할 일(Todo) 항목
"""
type Todo {
    id: ID!
    task: String!
    completed: Boolean!
    createdAt: String!
}