spring.application.name=spring-proj
spring.output.ansi.enabled=always

# ECOS API KEY
exchange.api.key=${ECOS_API_KEY}
exchange.api.base.url=${ECOS_BASE_URL}

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# DB
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Kakao Auth
kakao.client-id=${KAKAO_CLIENT_ID}
kakao.redirect-uri=${KAKAO_REDIRECT_URI}
kakao.auth-uri=${KAKAO_AUTH_URI}
kakao.token-uri=${KAKAO_TOKEN_URI}
kakao.user-info-uri=${KAKAO_USER_INFO_URI}
kakao.cookie-secure=false
kakao.front.redirect.url=${KAKAO_FRONT_REDIRECT}

# Swagger
springdoc.swagger-ui.operations-sorter=alpha