spring.application.name=spring-proj
spring.output.ansi.enabled=always

# ECOS API KEY
# exchange.api.key=${ECOS_API_KEY}
# exchange.api.base.url=${ECOS_BASE_URL}

# ECOS API KEY
exchange.api.key=PNLQVC1BJ9MNCY07OESM
exchange.api.base.url=https://ecos.bok.or.kr/api/StatisticSearch/

