spring.application.name=spring-proj
spring.output.ansi.enabled=always

# ECOS API KEY
exchange.api.key=${ECOS_API_KEY}
exchange.api.base.url=${ECOS_BASE_URL}

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# DB
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Kakao Auth
kakao.client-id=${KAKAO_CLIENT_ID}
kakao.redirect-uri=${KAKAO_REDIRECT_URI}
kakao.auth-uri=${KAKAO_AUTH_URI}
kakao.token-uri=${KAKAO_TOKEN_URI}
kakao.user-info-uri=${KAKAO_USER_INFO_URI}
kakao.front.redirect.url=${KAKAO_FRONT_REDIRECT}

# Cookie
kakao.cookie-secure=true
server.servlet.session.cookie.same-site=None

# Swagger
springdoc.swagger-ui.operations-sorter=alpha

# GraphQL
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql

# AI
ai.openai.api-key=${AI_GPT_KEY}
ai.gemini.api-key=${AI_GEMINI_KEY}
ai.claude.api-key=${AI_CLAUDE_KEY}

# Weather
weather.open-weather.api-key=${WEATHER_OPEN_WEATHER_KEY}